name: Operator
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  pull_request:
env:
  CGO_ENABLED: "0"
  GO_VERSION: "1.20"
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"
      - run: make verify
